# Generated by Django 5.2.9 on 2025-12-12 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_note_course_alter_note_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['title'], name='core_note_title_25b1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['course'], name='core_note_course_8b6681_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['tags'], name='core_note_tags_fda9b0_idx'),
        ),
    ]
