# Generated by Django 5.2.9 on 2025-12-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_note_core_note_title_25b1b2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
